#!/bin/bash
outPut=$(df -h | awk '{sub(/%/, "", $5);if($5>0) print $0}')

lines=$(echo "$outPut"| wc -l)
if [ $lines >1 ];
then echo "${outPut}"| sendmail -s "File System Alert on Host $(hostname -i)" <Mail_ID>
fi